{% set name = "grapheme" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/grapheme-{{ version }}.tar.gz
  sha256: 44c2b9f21bbe77cfb05835fec230bd435954275267fea1858013b102f8603cca

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}

test:
  imports:
    - grapheme
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/alvinlindstam/grapheme
  summary: Unicode grapheme helpers
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Brainor
